CREATE table Showcases(
                          uuid int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                          name varchar not null ,
                          address varchar not null ,
                          type varchar not null ,
                          datecreate date ,
                          datechange timestamp
);

GO
