CREATE table Product(
                        uuid int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                        showcases_id int references Showcases(uuid) on delete set null,
                        position int not null check ( price>0 ),
                        name varchar not null ,
                        type varchar not null ,
                        price decimal,
                        datecreate date ,
                        datechange timestamp
);

GO
